// Generated by CoffeeScript 1.7.1
(function() {
  var mailgun;

  mailgun = require("mailgun");

  mailgun.initialize("mg.onereminder.co", "key-1d18d71a2638337f57f73259704aa420");

  Parse.Cloud.afterSave("Contact", function(request) {
    var email;
    email = request.object.get('email');
    mailgun.sendEmail({
      to: "leo@onereminder.co",
      from: "beta@onereminder.co",
      subject: email + " has just registered for OneReminder Beta!",
      text: "Their email is: " + email
    }, {
      success: function(httpResponse) {
        console.log(httpResponse);
        console.log(email);
        return console.log("Email sent successfully");
      },
      error: function(httpResponse) {
        console.error(httpResponse);
        console.log(email);
        return console.error("Uh oh, something went wrong");
      }
    });
    return mailgun.sendEmail({
      to: email,
      from: "beta@onereminder.co",
      subject: "Thank you for joining OneReminder Beta",
      text: "You will receive an email from Apple's TestFlight system with your invitation to join OneReminder's beta.\n\nCheers and you're awesome!"
    }, {
      success: function(httpResponse) {
        console.log(httpResponse);
        console.log(email);
        return console.log("Email sent successfully");
      },
      error: function(httpResponse) {
        console.error(httpResponse);
        console.log(email);
        return console.error("Uh oh, something went wrong");
      }
    });
  });

}).call(this);
